name: Build and Deploy to Azure Web app

on:
    push:
        branches: 
            - live_testing

env:
    AZURE_WEBAPP_NAME: reactAppazure   # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: './build'      # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '18.0'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out Repo
              uses: actions/checkout@v4
            
            - name: Login in to azure
              uses: azure/login@v2
              with:
                creds: ${{secrets.AZURE_CREDENTIALS}}
            
            - name: Setup Node ${{env.NODE_VERSION}}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ env.NODE_VERSION }}

            - name: Build React Application
              run: |
                npm run install
                npm run build --if-present
              working-directory: .
            
            - name: Deploy react App to Azure web app
              uses: azure/webapps-deploy@v3
              with:
                app-name: ${{ env.AZURE_WEBAPP_NAME }}
                package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            
            - name: logout
              run: |
                az logout

